/**
 * @description:  诊断记录
 * 编号 id
 * 单位 unit
 * 诊断编号 diagnosticNumber
 * 诊断 diagnostic
 * 科室 department
 * 医生 doctor
 * 诊断类型 diagnosticType
 * 诊断分类 diagnosticClassify
 * 诊断状态 diagnosticState
 * 诊断日期 date
 * nodecode
 */
export const diagnosticRecord = [
  {id: 125445,
    unit: "南京医院",
    name: "阿莫西林",
    diagnosticNumber: 1254,
    diagnostic: "头痛",
    department: "内科",
    diagnosticType: "感冒",
    doctor: "张三",
    diagnosticClassify: "内科",
    diagnosticState: 1,
    nodecode: 1254841,
    date: "2021-9-23",
  },
  {
    id: 125446,
    unit: "西京医院",
    dataNum: 12,
    name: "阿莫西林",
    diagnosticNumber: 1254,
    diagnostic: "骨折",
    department: "鼻科",
    diagnosticType: "感冒",
    doctor: "张三",
    diagnosticClassify: "内科",
    diagnosticState: 1,
    nodecode: 1254841,
    date: "2021-9-23",
  },
  {
    id: 125447,
    unit: "南京医院",
    dataNum: 12,
    name: "阿莫西林",
    diagnosticNumber: 1254,
    diagnostic: "牙疼",
    department: "眼科",
    diagnosticType: "感冒",
    doctor: "张三",
    diagnosticClassify: "内科",
    diagnosticState: 1,
    nodecode: 1254841,
    date: "2021-9-23",
  },
  {
    id: 125448,
    unit: "西京医院",
    dataNum: 12,
    name: "阿莫西林",
    diagnosticNumber: 1254,
    diagnostic: "感冒",
    department: "耳科",
    diagnosticType: "感冒",
    doctor: "张三",
    diagnosticClassify: "内科",
    diagnosticState: 1,
    nodecode: 1254841,
    date: "2021-9-23",
  },
  {
    id: 125449,
    unit: "西京医院",
    dataNum: 12,
    name: "阿莫西林",
    diagnosticNumber: 1254,
    diagnostic: "皮疹",
    department: "骨科",
    diagnosticType: "感冒",
    doctor: "张三",
    diagnosticClassify: "内科",
    diagnosticState: 1,
    nodecode: 1254841,
    date: "2021-9-23",
  },
  {
    id: 1254410,
    unit: "南京医院",
    dataNum: 12,
    name: "阿莫西林",
    diagnosticNumber: 1254,
    diagnostic: "高血压",
    department: "皮肤科",
    diagnosticType: "感冒",
    doctor: "张三",
    diagnosticClassify: "内科",
    diagnosticState: 1,
    nodecode: 1254841,
    date: "2021-9-23",
  },
  {
    id: 1254411,
    unit: "南京医院",
    dataNum: 12,
    name: "阿莫西林",
    diagnosticNumber: 1254,
    diagnostic: "骨折",
    department: "骨科",
    diagnosticType: "感冒",
    doctor: "张三",
    diagnosticClassify: "内科",
    diagnosticState: 1,
    nodecode: 1254841,
    date: "2021-9-23",
  },
  {
    id: 1254412,
    unit: "南京医院",
    dataNum: 12,
    name: "阿莫西林",
    diagnosticNumber: 1254,
    diagnostic: "发烧",
    department: "门诊",
    diagnosticType: "感冒",
    doctor: "张三",
    diagnosticClassify: "内科",
    diagnosticState: 1,
    nodecode: 1254841,
    date: "2021-9-23",
  },
  {
    id: 1254413,
    unit: "西京医院",
    dataNum: 12,
    name: "阿莫西林",
    diagnosticNumber: 1254,
    diagnostic: "结膜炎",
    department: "门诊",
    diagnosticType: "感冒",
    doctor: "张三",
    diagnosticClassify: "内科",
    diagnosticState: 1,
    nodecode: 1254841,
    date: "2021-9-23",
  },
  {
    id: 1254414,
    unit: "南京医院",
    dataNum: 12,
    name: "阿莫西林",
    diagnosticNumber: 1254,
    diagnostic: "结膜炎",
    department: "骨科",
    diagnosticType: "感冒",
    doctor: "张三",
    diagnosticClassify: "内科",
    diagnosticState: 1,
    nodecode: 1254841,
    date: "2021-9-23",
  },
  {
    id: 1254415,
    unit: "南京医院",
    dataNum: 12,
    name: "阿莫西林",
    diagnosticNumber: 1254,
    diagnostic: "结膜炎",
    department: "骨科",
    diagnosticType: "感冒",
    doctor: "张三",
    diagnosticClassify: "内科",
    diagnosticState: 1,
    nodecode: 1254841,
    date: "2021-9-23",
  },
];
