/**
@description: 处方明细
编号  id
单位  unit
药品类别 drugType
药品名称  drugName  
数量  number
给药方式  doseType
是否皮试 isSkinTest
开单科室  billingDepartment
患者姓名  patientName
医生嘱托  DoctorAdvice
患者编号  patientNo
就诊IDs   visitIDS
*/

export const prescriptionDetails = [
  {
    id: 125445,
    unit: "南京医院",
    drugType: "西药",
    drugName: "阿莫西林",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "骨科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 125446,
    unit: "南京医院",
    drugType: "西药",
    drugName: "头孢氨苄西林钠",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "内科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 125447,
    unit: "南京医院",
    drugType: "西药",
    drugName: "阿莫西林",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "心内科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 125448,
    unit: "南京医院",
    drugType: "西药",
    drugName: "头孢氨苄西林钠",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "内科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 125449,
    unit: "南京医院",
    drugType: "西药",
    drugName: "阿莫西林",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "外科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 1254410,
    unit: "南京医院",
    drugType: "中药",
    drugName: "罗红霉素软膏",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "其他",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 1254411,
    unit: "南京医院",
    drugType: "西药",
    drugName: "阿莫西林",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "皮肤科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 1254412,
    unit: "南京医院",
    drugType: "西药",
    drugName: "罗红霉素软膏",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "耳科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 12544130,
    unit: "南京医院",
    drugType: "中药",
    drugName: "阿莫西林",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "儿科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 12544140,
    unit: "南京医院",
    drugType: "西药",
    drugName: "阿莫西林",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "骨科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 12544150,
    unit: "南京医院",
    drugType: "中药",
    drugName: "阿莫西林",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "鼻科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },{
    id: 1254450,
    unit: "南京医院",
    drugType: "西药",
    drugName: "阿莫西林",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "骨科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 1254460,
    unit: "南京医院",
    drugType: "西药",
    drugName: "头孢氨苄西林钠",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "内科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 1254470,
    unit: "南京医院",
    drugType: "西药",
    drugName: "阿莫西林",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "心内科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 1254480,
    unit: "南京医院",
    drugType: "西药",
    drugName: "头孢氨苄西林钠",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "内科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 1254490,
    unit: "南京医院",
    drugType: "西药",
    drugName: "阿莫西林",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "外科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 12544100,
    unit: "南京医院",
    drugType: "中药",
    drugName: "罗红霉素软膏",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "其他",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 12544110,
    unit: "南京医院",
    drugType: "西药",
    drugName: "阿莫西林",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "皮肤科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 12544120,
    unit: "南京医院",
    drugType: "西药",
    drugName: "罗红霉素软膏",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "耳科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 12544130,
    unit: "南京医院",
    drugType: "中药",
    drugName: "阿莫西林",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "儿科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 12544141,
    unit: "南京医院",
    drugType: "西药",
    drugName: "阿莫西林",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "骨科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
  {
    id: 12544151,
    unit: "南京医院",
    drugType: "中药",
    drugName: "阿莫西林",
    number: 3,
    doseType: 2,
    isSkinTest: "N",
    billingDepartment: "鼻科",
    patientName: "张三",
    DoctorAdvice: "wu",
    patientNo: 1254861,
    visitIDS: 1254841,
  },
];
