  /**
  * @description:  就诊表
  * 编号 id
    单位 unit
    就诊日期 strtDate
    医生编码 doctorNo
    医生 doctor
    患者编码 patientNo
    主诉 mainSuit
    现病史 HPI
    体格检查 ealthCheckup
    症状 symptom
    接诊次数 diagnosticTimes
    体温 temperature
    完成状态 state
    科室代码 departmentNo
    科室 department
    初复诊 iSInitial
    新兵否 isRecruit
    处置 management
    转诊医院 referralHospital
    门诊处置 outpatientTreatment
    reportedid
    reporteddate

  */
  export const visitRecord = [{
          id: 1254547,
          unit: '南京医院',
          strtDate: '2021-9-23',
          doctorNo: 1254,
          doctor: '张三',
          patientNo: 125874,
          mainSuit: '主诉',
          PI: '无',
          ealthCheckup: '正常',
          symptom: '感冒',
          diagnosticTimes: 1,
          temperature: 36.5,
          state: 1,
          departmentNo: 1025,
          department: '急诊',
          iSInitial: 'Y',
          isRecruit: 'N',
          management: '留观',
          referralHospital: '无',
          outpatientTreatment: '留观',
          reportedid: 1254,
          reporteddate: 1587
      },
      {
          id: 125446,
          unit: '南京医院',
          strtDate: '2021-9-23',
          doctorNo: 1254,
          doctor: '张三',
          patientNo: 125874,
          mainSuit: '主诉',
          PI: '无',
          ealthCheckup: '正常',
          symptom: '感冒',
          diagnosticTimes: 1,
          temperature: 36.5,
          state: 1,
          departmentNo: 1025,
          department: '急诊',
          iSInitial: 'Y',
          isRecruit: 'N',
          management: '留观',
          referralHospital: '无',
          outpatientTreatment: '留观',
          reportedid: 1254,
          reporteddate: 1587
      },
      {
          id: 125447,
          unit: '南京医院',
          strtDate: '2021-9-23',
          doctorNo: 1254,
          doctor: '张三',
          patientNo: 125874,
          mainSuit: '主诉',
          PI: '无',
          ealthCheckup: '正常',
          symptom: '感冒',
          diagnosticTimes: 1,
          temperature: 36.5,
          state: 1,
          departmentNo: 1025,
          department: '急诊',
          iSInitial: 'Y',
          isRecruit: 'N',
          management: '留观',
          referralHospital: '无',
          outpatientTreatment: '留观',
          reportedid: 1254,
          reporteddate: 1587
      },
      {
          id: 125448,
          unit: '南京医院',
          strtDate: '2021-9-23',
          doctorNo: 1254,
          doctor: '张三',
          patientNo: 125874,
          mainSuit: '主诉',
          PI: '无',
          ealthCheckup: '正常',
          symptom: '感冒',
          diagnosticTimes: 1,
          temperature: 36.5,
          state: 1,
          departmentNo: 1025,
          department: '急诊',
          iSInitial: 'Y',
          isRecruit: 'N',
          management: '留观',
          referralHospital: '无',
          outpatientTreatment: '留观',
          reportedid: 1254,
          reporteddate: 1587
      },
      {
          id: 125449,
          unit: '南京医院',
          strtDate: '2021-9-23',
          doctorNo: 1254,
          doctor: '张三',
          patientNo: 125874,
          mainSuit: '主诉',
          PI: '无',
          ealthCheckup: '正常',
          symptom: '感冒',
          diagnosticTimes: 1,
          temperature: 36.5,
          state: 1,
          departmentNo: 1025,
          department: '急诊',
          iSInitial: 'Y',
          isRecruit: 'N',
          management: '留观',
          referralHospital: '无',
          outpatientTreatment: '留观',
          reportedid: 1254,
          reporteddate: 1587
      },
      {
          id: 1254410,
          unit: '南京医院',
          strtDate: '2021-9-23',
          doctorNo: 1254,
          doctor: '张三',
          patientNo: 125874,
          mainSuit: '主诉',
          PI: '无',
          ealthCheckup: '正常',
          symptom: '感冒',
          diagnosticTimes: 1,
          temperature: 36.5,
          state: 1,
          departmentNo: 1025,
          department: '急诊',
          iSInitial: 'Y',
          isRecruit: 'N',
          management: '留观',
          referralHospital: '无',
          outpatientTreatment: '留观',
          reportedid: 1254,
          reporteddate: 1587
      },
      {
          id: 1254411,
          unit: '南京医院',
          strtDate: '2021-9-23',
          doctorNo: 1254,
          doctor: '张三',
          patientNo: 125874,
          mainSuit: '主诉',
          PI: '无',
          ealthCheckup: '正常',
          symptom: '感冒',
          diagnosticTimes: 1,
          temperature: 36.5,
          state: 1,
          departmentNo: 1025,
          department: '急诊',
          iSInitial: 'Y',
          isRecruit: 'N',
          management: '留观',
          referralHospital: '无',
          outpatientTreatment: '留观',
          reportedid: 1254,
          reporteddate: 1587
      },
      {
          id: 1254412,
          unit: '南京医院',
          strtDate: '2021-9-23',
          doctorNo: 1254,
          doctor: '张三',
          patientNo: 125874,
          mainSuit: '主诉',
          PI: '无',
          ealthCheckup: '正常',
          symptom: '感冒',
          diagnosticTimes: 1,
          temperature: 36.5,
          state: 1,
          departmentNo: 1025,
          department: '急诊',
          iSInitial: 'Y',
          isRecruit: 'N',
          management: '留观',
          referralHospital: '无',
          outpatientTreatment: '留观',
          reportedid: 1254,
          reporteddate: 1587
      },
      {
          id: 1254413,
          unit: '南京医院',
          strtDate: '2021-9-23',
          doctorNo: 1254,
          doctor: '张三',
          patientNo: 125874,
          mainSuit: '主诉',
          PI: '无',
          ealthCheckup: '正常',
          symptom: '感冒',
          diagnosticTimes: 1,
          temperature: 36.5,
          state: 1,
          departmentNo: 1025,
          department: '急诊',
          iSInitial: 'Y',
          isRecruit: 'N',
          management: '留观',
          referralHospital: '无',
          outpatientTreatment: '留观',
          reportedid: 1254,
          reporteddate: 1587
      },
      {
          id: 1254414,
          unit: '南京医院',
          strtDate: '2021-9-23',
          doctorNo: 1254,
          doctor: '张三',
          patientNo: 125874,
          mainSuit: '主诉',
          PI: '无',
          ealthCheckup: '正常',
          symptom: '感冒',
          diagnosticTimes: 1,
          temperature: 36.5,
          state: 1,
          departmentNo: 1025,
          department: '急诊',
          iSInitial: 'Y',
          isRecruit: 'N',
          management: '留观',
          referralHospital: '无',
          outpatientTreatment: '留观',
          reportedid: 1254,
          reporteddate: 1587
      },
      {
          id: 1254415,
          unit: '南京医院',
          strtDate: '2021-9-23',
          doctorNo: 1254,
          doctor: '张三',
          patientNo: 125874,
          mainSuit: '主诉',
          PI: '无',
          ealthCheckup: '正常',
          symptom: '感冒',
          diagnosticTimes: 1,
          temperature: 36.5,
          state: 1,
          departmentNo: 1025,
          department: '急诊',
          iSInitial: 'Y',
          isRecruit: 'N',
          management: '留观',
          referralHospital: '无',
          outpatientTreatment: '留观',
          reportedid: 1254,
          reporteddate: 1587
      }

  ]